ci: add refactored auto release pipeline
Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>

diff --git a/.github/workflows/autorelease.yml b/.github/workflows/autorelease.yml
--- a/.github/workflows/autorelease.yml
+++ b/.github/workflows/autorelease.yml
@@ -3,12 +3,16 @@ name: Auto Release
 on:
   push:
     branches:
-      - "master"
+      - "main"
   workflow_dispatch:
     inputs:
       bump-version:
         description: 'Automatically increase patch version (true|false)'
         default: 'true'
+        required: false
+      release-type:
+        description: 'Type of release (patch|minor|major)'
+        default: 'patch'
         required: false
 
 env:
@@ -20,7 +24,6 @@ jobs:
   release:
 
     runs-on: ubuntu-latest
-    if: github.repository == 'priv-kweihmann/oelint-adv'
 
     steps:
     - name: Checkout
@@ -35,7 +38,13 @@ jobs:
         if [ -z "${{ secrets.TOKEN }}" ]; then
           echo "::error ::secrets.TOKEN needs to be set for this action"
           exit 1
-        fi        
+        fi
+        if [ "${{ github.event_name == 'workflow_dispatch' }}" = "true" ]; then
+          if [ -z "${{ github.event.inputs.release-type }}" ]; then
+            echo "::error ::release-type cannot be empty"
+            exit 1
+          fi
+        fi
 
     - name: Check if relevant for release
       uses: dorny/paths-filter@v2.11.1
@@ -45,8 +54,6 @@ jobs:
           relevant-for-release:
             - 'requirements.txt'
             - '${{ env.MODULE_CODE }}'
-          manual-bumped-version:
-            - '.bumpversion'
 
     - name: Check if we need to release
       id: release-needed
@@ -54,16 +61,15 @@ jobs:
         do_release=0
         do_bump=0
         [ "${{ steps.code-changes.outputs.relevant-for-release == 'true' }}" = "true" ] && do_release=1
-        [ "${{ steps.code-changes.outputs.manual-bumped-version != 'true' }}" = "true" ] && [ $do_release -eq 1 ] && do_bump=1
         if [ "${{ github.event_name == 'workflow_dispatch' }}" = "true" ]; then
           do_release=1
-          [ "${{ github.inputs.bump-version }}" = "true" ] && do_bump=1
+          [ "${{ github.event.inputs.bump-version }}" = "true" ] && do_bump=1
         fi
 
-        if [ $do_bump -eq 1 ]; then
-          echo DO_BUMP=true >> $GITHUB_OUTPUT
+        if [ "${{ github.event_name == 'workflow_dispatch' }}" = "true" ]; then
+          echo RELEASE_TYPE="${{ github.event.inputs.release-type }}" >> $GITHUB_OUTPUT
         else
-          echo DO_BUMP=false >> $GITHUB_OUTPUT
+          echo RELEASE_TYPE="patch" >> $GITHUB_OUTPUT
         fi
 
         if [ $do_release -eq 1 ] || [ $do_bump -eq 1 ]; then
@@ -80,10 +86,9 @@ jobs:
     
     - name: Bump version
       id: version-bump
-      if: steps.release-needed.outputs.DO_BUMP == 'true'
       run: |
         pip install -r requirements-dev.txt
-        bump2version --list patch ${{ env.VERSION_FILE }} >> $GITHUB_OUTPUT
+        bump2version --list ${{ steps.release-needed.outputs.RELEASE_TYPE }} ${{ env.VERSION_FILE }} >> $GITHUB_OUTPUT
       
     - name: Build
       if: steps.release-needed.outputs.DO_RELEASE == 'true'
@@ -91,7 +96,7 @@ jobs:
         python3 setup.py build sdist bdist_wheel --universal
 
     - name: Commit new version
-      if: steps.release-needed.outputs.DO_BUMP == 'true'
+      if: steps.release-needed.outputs.DO_RELEASE == 'true'
       uses: actions-x/commit@v6
       with:
         message: 'Release ${{ steps.version-bump.outputs.new_version }}'
